# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
# title: Benjamin的聚落
# subtitle: Dream bigger and act boldly
# description: Stay hungry and stay foolish
# keywords: Benjamin的聚落
# author: Benjamin
# language: zh-TW
# timezone: ''
# email: ba81764937@gmail.com

# # URL
# ## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
# url: https://SkysRabbit.github.io
# # permalink: :year/:month/:day/:title/
# permalink: posts/:title/
# permalink_defaults:
# pretty_urls:
#   trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
#   trailing_html: true # Set to false to remove trailing '.html' from permalinks

# theme configuration
nav:
  logo: # image
  display_title: true
  fixed: false

# top menu(參考streamlit logo)
menu: 
  Home: / || fas fa-home
  Tech || fas fa-robot:
    Web: /web/
    Machine Learning: /ml/
  About: /about || fas fa-heart

# code highlighting
highlight_theme: mac
highlight_copy: true
highlight_shrink: false # unfold default
highlight_height_limit: false # unit: px

# Social setting
social:
  fab fa-github: https://xxxxxxx || GitHub || "hdhfbb"

# avatar
avator:
  img:
  effect: true

# post cover
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover: 

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

post_meta:
  page:
    date_type: both
    date_format: relative
    categories: true
    tags: true
    label: true
  post:
    date_type: both
    date_format: relative
    categories: true
    tags: true
    label: true 

# anchor
anchor:
  auto_update: false
  click_to_scroll: true

photofigcaption: false

error_404:
  enable: true
  subtitle: '找不到此頁面'
  background: 

post_copyright:
  enable: true
  decode: true
  author_href:

toc:
  post: true
  page: false
  number: true
  expand: true
  style_simple: false # for post
  scroll_percent: true

related_post:
  enable: true
  limit: 4
  date_type: created

footer:
  owner:
    enable: true
    since: 2024
  custom_text:
  copyright: true # copyright of theme and framework

# add read mode
readmode: true

darkmode:
  enable: true
  button: true
  autoChangeMode: true
  start: # 8
  end: # 22

rightside_scroll_percent: true

# note標籤
note:
  style: modern # simple
  icons: false
  border_radius: 3
  light_bg-offset: 0

  # The user interface setting of category and tag page (category和tag頁的UI設置)
# index - same as Homepage UI (index 值代表 UI將與首頁的UI一樣)
# default - same as archives UI 默認跟archives頁面UI一樣
category_ui: index # 留空或 index
tag_ui: index # 留空或 index

# Stretches the lines so that each line has equal width（文字向兩側對齊，對最後一行無效）
text_align_justify: false

# Website Background (設置網站背景)
# can set it to color or image (可設置圖片 或者 顔色)
# The formal of image: url(http://xxxxxx.com/xxx.jpg)
background:

# Footer Background
footer_bg: true

# Add mask to header or footer (為 header 或 footer 添加黑色半透遮罩)
mask:
  header: true
  footer: true

# the position of bottom right button/default unit: px (右下角按鈕距離底部的距離/默認單位為px)
rightside_bottom:

# Enter transitions (開啓網頁進入效果)
enter_transitions: true

# Typewriter Effect (打字效果)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: false
  colorful: true # open particle animation (冒光特效)
  shake: true #  open shake (抖動特效)
  mobile: false

# Background effects (背景特效)
# --------------------------------------

# canvas_ribbon (靜止彩帶背景)
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: true
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: true
  mobile: true

# Fluttering Ribbon (動態彩帶)
canvas_fluttering_ribbon:
  enable: false
  mobile: false

# canvas_nest
# https://github.com/hustcc/canvas-nest.js
canvas_nest:
  enable: false
  color: '0,0,255' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  mobile: false

# Mouse click effects: fireworks (鼠標點擊效果: 煙火特效)
fireworks:
  enable: false
  zIndex: 9999 # -1 or 9999
  mobile: false

# Mouse click effects: Heart symbol (鼠標點擊效果: 愛心)
click_heart:
  enable: false
  mobile: false

# Mouse click effects: words (鼠標點擊效果: 文字)
clickShowText:
  enable: false
  text:
    # - I
    # - LOVE
    # - YOU
  fontSize: 15px
  random: false
  mobile: false

# Default display mode (網站默認的顯示模式)
# light (default) / dark
display_mode: 

# Beautify (美化頁面顯示)
beautify:
  enable: true
  field: post # site/post
  title-prefix-icon: '\f004' #'\f0c1' # put unicode here
  title-prefix-icon-color: '#F47466'

# Global font settings
# Don't modify the following settings unless you know how they work (非必要不要修改)
font:
  global-font-size:
  code-font-size:
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Lato, Roboto, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif
  code-font-family: consolas, Menlo, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif

# Font settings for the site title and site subtitle
# 左上角網站名字 主頁居中網站名字
blog_title_font:
  font_link: https://fonts.googleapis.com/css?family=Titillium+Web&display=swap
  font-family: Titillium Web, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft JhengHei', 'Microsoft YaHei', sans-serif

# The setting of divider icon (水平分隔線圖標設置)
hr_icon:
  enable: true
  icon: # the unicode value of Font Awesome icon, such as '\3423'
  icon-top:

# the subtitle on homepage (主頁subtitle)
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # Customize typed.js (配置typed.js)
  # https://github.com/mattboldt/typed.js/#customization
  typed_option:
    loop: true
  # source 調用第三方服務
  # source: false 關閉調用
  # source: 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # source: 2  調用一句網（簡體） https://yijuzhan.com/
  # source: 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: 0
  # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
  sub:
    - 積少成多，聚沙成塔
    - Everything starts from tiny scratch


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# # Include / Exclude file(s)
# ## include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
# ignore:

# # Extensions
# ## Plugins: https://hexo.io/plugins/
# ## Themes: https://hexo.io/themes/
# theme: butterfly

# # Deployment
# ## Docs: https://hexo.io/docs/one-command-deployment
# deploy: 
#   type: git
#   repo: https://github.com/SkysRabbit/SkysRabbit.github.io.git
#   branch: gh-pages
